# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{google_static_maps_helper}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Thorbj\303\270rn Hermansen"]
  s.date = %q{2009-10-13}
  s.description = %q{This gem provides a simple interface to the Google Static Maps V2 API.}
  s.email = %q{thhermansen@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "google_static_maps_helper.gemspec",
     "lib/google_static_maps_helper.rb",
     "lib/google_static_maps_helper/map.rb",
     "lib/google_static_maps_helper/marker.rb",
     "spec/map_spec.rb",
     "spec/marker_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/thhermansen/google_static_maps_helper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{This gem provides a simple interface to the Google Static Maps V2 API}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/marker_spec.rb",
     "spec/map_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end
